task buildPaddleLite(type: Exec) {
    environment 'LITE_BUILD_THREADS', 8 // TODO: Change
    environment 'NDK_ROOT', "android.ndkDirectory"
    environment 'NDK_NAME', 'android-ndk-r25c'
    def sharedFlags = "--android_stl=c++_shared --with_extra=ON --with_cv=ON --with_log=OFF --with_exception=OFF --with_nnadapter=ON --nnadapter_with_android_nnapi=ON --android_api_level=33"

    doFirst {
        if (arch == 'armv8') {
            exec {
                commandLine '../PaddleLite/lite/tools/build_android.sh', '--with_arm82_fp16=ON', '--with_arm8_sve2=ON', sharedFlags
            }
        } else if (arch == 'armv7') {
            exec {
                commandLine '../PaddleLite/lite/tools/build_android.sh', '--arch=armv7', sharedFlags
            }
        } else {
            println "Unsupported architecture: $arch"
        }
    }
}

task buildOpenCV(type: Exec) {
    environment 'ANDROID_COMPILE_SDK', 'android-33'
    environment 'ANDROID_SDK', '/opt/Android'
    environment 'JAVA_HOME', '/usr/lib/jvm/java-17-openjdk-amd64'
    environment 'ANDROID_HOME', '/opt/Android'

    doFirst {
        if (arch == 'armv8') {
            exec {
                commandLine 'python3', "../jniLibs/platforms/android/build_sdk.py", "../jniLibs", "opencv", '--ndk_path', "android.ndkDirectory", '--sdk_path', "$ANDROID_SDK", '--config', './opencv-ndk.config.py', '--no_samples_build', '--java_version', '17', '--android_target_sdk', targetSdk, '--android_compile_sdk', compileSdk, '--android_min_sdk', minSdk, '--arch', arch, '--arch', arch
            }
        } else if (arch == 'armv7') {
            exec {
                    commandLine 'python3', "../jniLibs/platforms/android/build_java_shared_aar.py", "../jniLibs/OpenCV-android-sdk", '--java_version', '17', '--android_target_sdk', targetSdk, '--android_compile_sdk', compileSdk, '--android_min_sdk', minSdk, '--arch', arch
            }
        } else {
            println "Unsupported architecture: $arch"
        }
    }
}

task cleanOpenCV {
    doLast {
        def defaultArchitectures = ['armv7', 'armv8']
        def architectures = project.hasProperty('architectures') ? project.architectures.split(',') : defaultArchitectures

        if (arch == 'armv8') {
            delete "jniLibs/OpenCV-android-sdk/armv8"
        } else if (arch == 'armv7') {
            delete "jniLibs/OpenCV-android-sdk/armv7"
        } else if (architectures.contains('armv8') && architectures.contains('armv7')) {
            delete "jniLibs/OpenCV-android-sdk"
        } else {
            println "Unsupported architecture: $arch"
        }
    }
}

task cleanPaddleLite {
    doLast {
        delete "jniLibs/Paddle-Lite"
    }
}

task ndkClean {
    doLast{
        dependsOn cleanOpenCV
        dependsOn cleanPaddleLite
    }
}

task ndkCleanAll {
    doLast {
        delete "jniLibs"
    }
}